### ISSUE TITLE
Make mime-detective cross-platform

### ISSUE THREAD

**Issue by pepsighan** [csharad/mime-detective#3]
Continued https://github.com/csharad/mime-detective/issues/1#issuecomment-464310889

To make mime-detective cross-platform, we need to statically store the `.mgc` files in the binary itself so that it does not look for the installed magic definitions in the target systems.

**Comment by ElXreno** [comment]
Some news here?

**Comment by pepsighan** [comment]
Thanks for the notification. Had forgotten about the issue.

I have made the changes and published a new version.
